/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class StyleConstants {
  public static DEFAULT_FONT_COLOR: string = '#ffffff'
  public static WIDTH: string = '100%';
  public static DIALOG_WIDTH: number = 440;
  public static DIALOG_PADDING: number = 24;
  public static DIALOG_TITLE_TOP: number = 20;
  public static DIALOG_TITLE_BOTTOM: number = 25;
  public static DIALOG_BUTTON_WIDTH: number = 196;
  public static DIALOG_BUTTON_WIDTH2: number = 392;
  public static DIALOG_BUTTON_HEIGHT: number = 45;
  public static ICON_WIDTH: number = 25;
  public static ICON_HEIGHT: number = 35;
  public static BACK_ICON_HEIGHT: number = 60;
  public static BACK_ICON_WIDTH: number = 30;
  public static RADIO_SIZE: number = 25;
  public static TOGGLE_SIZE: number = 40;
  public static TOGGLE_BOX_SIZE: number = 50;
  public static SINGLE_HEIGHT: number = 68;
  public static SINGLE_HEIGHT_: number = 55;
  public static DOUBLE_HEIGHT_: number = 68;
  public static DIVIDER: number = 1;
  public static BORDER_RADIUS: number = 20;
  public static PADDING: number = 14;
  public static PADDING_30: number = 30;
  public static PADDING_4: number = 4;
  public static TEXT_PADDING: number = 10;
  public static TEXT_PADDING2: number = 20;
  public static GERY_BORDER_PADDING: number = 16;
  public static WHITE_BACKGROUND_COLOR: string = '#FFFFFF';
  public static GREY_BACKGROUND_COLOR: string = '#F2F3F5';
  public static DARK_GREY_BACKGROUND_COLOR: string = '#E5E6E8';
  public static GREY_FONT_COLOR: string = '#5B5C5E';
  public static BLUE_FONT_COLOR: string = '#0A58F6';
  public static SMALL_FONT_SIZE: number = 17;
  public static MEDIUM_FONT_SIZE: number = 18;
  public static LARGE_FONT_SIZE: number = 19;
  public static OVERSIZE_FONT_SIZE: number = 22;
}