/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class StyleConstants {
  public static MAX_WIDTH: string = '100%';
  public static MAX_HEIGHT: string = '100%';
  public static ITEM_WIDTH: string = '93%';
  public static BACK_WIDTH: string = '15%';
  public static TITLE_TEXT_WIDTH: string = '60%';
  public static TITLE_HEIGHT: string = '10%';
  public static PHONE_WIDTH: string = '33%';
  public static PHONE_HEIGHT: string = '30%';
  public static LIST_TEXT_HEIGHT: string = '50%';
  public static INTO_ARROW_WIDTH: string = '5%';
  public static INTO_ARROW_HEIGHT: number = 50;
  public static CONTENT_TIPS_WIDTH: string = '85%';
  public static CONTENT_TIPS_HEIGHT: number = 84  ;
  public static PADDING: number = 18;
  public static PADDING_30: number = 30;
  public static PADDING_4: number = 4;
  public static UNLOCK_TEXT_WIDTH: string = '75%';
  public static UNLOCK_TEXT_HEIGHT: number = 84;
  public static ITEM_BORDER_RADIO: number = 30;
  public static TRUSTED_TEXT_HEIGHT: number = 50;
  public static TRUSTED_TEXT_MARGIN_LEFT: number = 30;
  public static TRUSTED_TEXT_MARGIN_TOP: number = 32 ;
  public static TRUSTED_TEXT_MARGIN_BOTTOM: number = 18;
  public static LIST_ITEM_MARGIN_BOTTOM: number = 18 ;
  public static LIST_ITEM_MARGIN_TOP: number = 18;
  public static LIST_ITEM_MARGIN_LEFT: number = 18;
  public static ADD_TEXT_HEIGHT: number = 88;
  public static ADD_TEXT_MARGIN_BOTTOM: number = 10;
  public static ADD_TEXT_MARGIN_TOP: number = 10;
  public static ADD_TEXT_MARGIN_LEFT: number = 25;
  public static LIST_ITEM_HEIGHT: number = 100;
  public static LIST_SPACE: number = 10;
  public static SCROLLBAR_WIDTH: number = 0;
  public static BACK_PADDING: number = 15;
  public static PHONE_MARGIN_TOP: number = 30;
  public static PHONE_MARGIN_BOTTOM: number = 15;
  public static DIALOG_TITLE_HEIGHT: number = 65;
  public static DIALOG_TITLE_MARGIN_BOTTOM: number = 30;
  public static DIALOG_TITLE_MARGIN_TOP: number = 25;
  public static DIALOG_TEXT_MARGIN_BOTTOM: number = 20;
  public static DIALOG_OPTION_TEXT_HEIGHT: number = 55;
  public static DIALOG_OPTION_MARGIN: number = 15;
  public static DIALOG_DRIVER_HEIGHT: number = 30;
  public static DIALOG_DRIVER_STROKE_WIDTH: number = 2;
  public static DIALOG_LIST_MARGIN: number = 10;
  public static DIALOG_ADD_TIPS_HEIGHT: number = 150;
  public static DIALOG_IS_ADD_HEIGHT: number = 50;
  public static REMOVE_DIALOG_HEIGHT: number = 250;
  public static USER_TIPS_DIALOG_HEIGHT: number = 350;
  public static ADD_DIALOG_HEIGHT: number = 410;
  public static WHITE_BACKGROUND_COLOR: string = '#FFFFFF';
  public static GREY_BACKGROUND_COLOR: string = '#F2F3F5';
  public static DARK_GREY_BACKGROUND_COLOR: string = '#E5E6E8';
  public static DARK_GREY_FONT_COLOR: string = '#5B5C5E';
  public static GREY_FONT_COLOR: string = '#808080';
  public static BLUE_FONT_COLOR: string = '#0A58F6';
  public static RED_FONT_COLOR: string = '#FF4500';
  public static RED_BACKGROUND_COLOR: string = '#F0E9E9';
  public static BLACK_FONT_COLOR: string = "#000000";
  public static MIN_FONT_SIZE: number = 20;
  public static TITLE_FONT_SIZE: number = 30;
  public static TEXT_FONT_SIZE: number = 23;
  public static OPTION_FONT_SIZE: number = 25;
}
