/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class StyleConstants {
  public static MAX_WIDTH: string = '100%';
  public static MAX_HEIGHT: string = '100%';
  public static ITEM_WIDTH: string = '93%';
  public static BACK_WIDTH: number = 30;
  public static BACK_HEIGHT: number = 60;
  public static PADDING_30: number = 30;
  public static TITLE_TEXT_WIDTH: string = '60%';
  public static TITLE_HEIGHT: number = 70;
  public static PADDING: number = 14;
  public static PHONE_WIDTH: string = '50%';
  public static PHONE_HEIGHT: string = '30%';
  public static LIST_TEXT_HEIGHT: string = '50%';
  public static SMALL_INFO_ARROW_WIDTH: number = 15;
  public static INTO_ARROW_WIDTH: number = 25;
  public static INTO_ARROW_HEIGHT: number = 35;
  public static CONTENT_TIPS_HEIGHT: number = 68;
  public static ITEM_BORDER_RADIO: number = 20;
  public static TRUSTED_TEXT_HEIGHT: number = 50;
  public static TRUSTED_TEXT_MARGIN_LEFT: number = 30;
  public static TRUSTED_TEXT_MARGIN_TOP: number = 25;
  public static TRUSTED_TEXT_MARGIN_BOTTOM: number = 10;
  public static LIST_ITEM_MARGIN_BOTTOM: number = 20;
  public static LIST_ITEM_MARGIN_TOP: number = 20;
  public static LIST_ITEM_MARGIN_LEFT: number = 25;
  public static ADD_TEXT_HEIGHT: number = 88;
  public static ADD_TEXT_MARGIN_BOTTOM: number = 10;
  public static ADD_TEXT_MARGIN_TOP: number = 10;
  public static ADD_TEXT_MARGIN_LEFT: number = 25;
  public static LIST_ITEM_HEIGHT: number = 70;
  public static LIST_ITEM_HEIGHT_: number = 68;
  public static LIST_SPACE: number = 10;
  public static SCROLLBAR_WIDTH: number = 0;
  public static BACK_PADDING: number = 15;
  public static PHONE_MARGIN_TOP: number = 10;
  public static PHONE_MARGIN_BOTTOM: number = 10;
  public static TEXT_MARGIN_TOP: number = 6;
  public static TEXT_MARGIN_BOTTOM: number = 6;

  public static DIALOG_OPTION_TEXT_HEIGHT: number = 55;
  public static DIALOG_OPTION_MARGIN: number = 15;
  public static DIALOG_DRIVER_HEIGHT: number = 30;
  public static DIALOG_DRIVER_STROKE_WIDTH: number = 1;
  public static DIALOG_LIST_MARGIN: number = 10;
  public static DIALOG_ADD_TIPS_HEIGHT: number = 150;
  public static DIALOG_IS_ADD_HEIGHT: number = 50;
  public static REMOVE_DIALOG_HEIGHT: number = 250;
  public static USER_TIPS_DIALOG_HEIGHT: number = 350;
  public static WHITE_BACKGROUND_COLOR: string = '#FFFFFF';
  public static GREY_BACKGROUND_COLOR: string = '#F2F3F5';
  public static DARK_GREY_BACKGROUND_COLOR: string = '#E5E6E8';
  public static DARK_GREY_FONT_COLOR: string = '#5B5C5E';
  public static GREY_FONT_COLOR: string = '#808080';
  public static LIGHT_GREY_FONT_COLOR: string = '#A1A1A1';
  public static LIGHT_GREY_FONT_COLOR2: string = '#CBCBCB';
  public static BLUE_FONT_COLOR: string = '#0A58F6';
  public static RED_FONT_COLOR: string = '#FF4500';
  public static BLACK_FONT_COLOR: string = "#000000";
  public static TOGGLE_SIZE: number = 40;
  public static MIN_FONT_SIZE: number = 18;
  public static TEXT_FONT_SIZE: number = 19;
  public static OPTION_FONT_SIZE: number = 22;
  public static DIALOG_WIDTH: number = 440;
  public static DIALOG_PADDING: number = 24;
  public static DIALOG_TITLE_TOP: number = 20;
  public static DIALOG_TITLE_BOTTOM: number = 25;
  public static DIALOG_TITLE_HEIGHT: number = 40;
  public static DIALOG_TITLE_MARGIN_TOP: number = 10;
  public static DIALOG_TITLE_MARGIN_BOTTOM: number = 10;
  public static DIALOG_TEXT_BOTTOM: number = 16;
  public static DIALOG_BUTTON_WIDTH: number = 196;
  public static DIALOG_BUTTON_HEIGHT: number = 45;
  public static PADDING_4: number = 4;
}
